### ISSUE TITLE
Fishing message not working correctly

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#121]
I do not receive the ''You caughted a fish'' message in my actionbar as of 4.3.8.

mobhunting.fishcaught.reward=&7Je hebt een vis gevangen en &3${prize} &7verdiend!

**Comment by Sikatsu** [comment]
@Rocologo 

I noticed that I didn't update TitleManager on the test server, however even when I updated it the messages still don't appear in the actionbar for fishing. (The old version when it still used moneygain, worked)

**Comment by Rocologo** [comment]
It works on my testserver on build 265, but I dont know if I have a problem with TitleManager.

Please test build 265 and let me know if it works. If it still dont work I need to know which version of TitleManager you use.

Its starting to become a problem that I cant control the time the ActionBar Message is shown. I think I need to find a solution to this.... hmm...

**Comment by Sikatsu** [comment]
I will test this now.

**Comment by Sikatsu** [comment]
@Rocologo 

This is still not fixed. I do receive a message when I kill mobs, but not when I fish. I'm using TitleManager 2.0.6.

Weird, because when you still had it on ''moneygain'' the message was displayed, until you made an own language line for this.

**Comment by Sikatsu** [comment]
@Rocologo 

Not fixed on build B266. (Not sure if it was meant to be fixed)

**Comment by Rocologo** [comment]
Im confused about this one, which message is you dont get?

**Comment by Sikatsu** [comment]
mobhunting.fishcaught.reward=

This one ^

I receive every message in my actionbar, but when I catch a fish I do not get any message that I catched a fish and received money.

**Comment by Rocologo** [comment]
I can now replicate the error on my server too, so now I will be able to fix this.

**Comment by Sikatsu** [comment]
Awesome! You also fixed the fish head issue I just noticed, now the only issue remaining will be.. money rewards for junk.

**Comment by Rocologo** [comment]
Dont mix all the tickets you have made ;-)

This one is fixed in V4.4.1-SNAPSHOT
Build 269

http://jenkins.lindegaard.one:8180/job/MobHunting/

I could suddenly replicate the bug and have solved it now.

I need some sleep now... I close this ticket...

**Comment by Sikatsu** [comment]
Sorry :P

**Comment by Rocologo** [comment]
No worries I very thank ful that you are willing to help me testing. Its hars to do all alone.

**Comment by Sikatsu** [comment]
@Rocologo 

I'm afraid this is not fixed - it actually makes things worser. I am not receiving any money for fishing anymore nor the message that I received money.
