### ISSUE TITLE
It's possible to stack heads of different mobs

### ISSUE THREAD

**Issue by skerit** [Rocologo/MobHunting#583]
It's possible to stack a mob head of (for example) a zombie and a skeleton.

The head you place on another stack gets turned into that other head.

So putting a zombie head on a stack of skeleton heads will give you one extra skeleton head. Not exactly duping, but not really good either.

**Comment by Momshroom** [comment]
I'm having this same issue, except the issue doesn't always happen.
I haven't been able to tell what causes it and I have no console errors, but once a stack accepts extra mob heads, it always seems to.

Video of glitch:
https://www.youtube.com/watch?v=9zyK5pX-aPU

Mobhunting 6.9.6
Paper 236 (1.14.4)

**Comment by Onyxtite** [comment]
Truly worrying in my opinion, hopefully a fix is on the way :)

**Comment by Rocologo** [comment]
Fixed in next release - i hope :-)

**Comment by Momshroom** [comment]
This is still broken in 6.9.9.  Sorry.

**Comment by Rocologo** [comment]
I have tested the skeleton and a zombie head and was not able to stack them, so I need more information solve this puzzle. Which heads could you stack and did they have a value or not? Both of them?

**Comment by Momshroom** [comment]
I was stacking pigmen heads with vex heads. (Turning pigmen into vex)
Works turning vex into pigmen as well.  https://prnt.sc/qlo1n7 the data after converting a vex into a pigman.
I got the heads with /mh head give ...

**Comment by Momshroom** [comment]
This is still broken.  Get a vex head and a pigman head. (/mh head give Momshroom vex, /mh head give momshroom ZombiePigman)  You can stack the pigman head onto the vex head and have two vex heads.

**Comment by mrfloris** [comment]
```
>ver MobHunting
[01:19:55] [Server thread/INFO]: MobHunting version 7.0.0
[01:19:55] [Server thread/INFO]: MobHunting adds a new level of fun to hunting monsters. Now you can get money from kills, get bonuses for skilled and creative kills, and get special achievements.
[01:19:55] [Server thread/INFO]: Author: Rocologo
>ver
[01:19:55] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-8faa8b4-13ed05d (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[01:19:55] [Server thread/INFO]: Checking version, please wait...
[01:19:56] [Thread-206/INFO]: You are running the latest version
>
```

Players can reproduce this on first try.

**Comment by mrfloris** [comment]
Friendly bump, this allows users to impact economy on servers by taking stack of inexpensive heads and turn them into rare ones and getting mucho mula for it. 

Looking for a real fix ~ otherwise we're just forced to uninstall this on the network. Especially since there's now also a stack item dupe bug report out.

**Comment by Momshroom** [comment]
I'm NOT able to reproduce this with only Spigot (This server is running CraftBukkit version git-Spigot-6de3d4b-fc24934 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) and mob hunting, but I am with just:
Mobhunting, Vault, iConomy5.0.9 on the same version of Spigot.  
Hope this helps!

**Comment by Momshroom** [comment]
Also possible to replicate this with TheNewEconomy instead of iConomy.  Seems to just be having mobhunting and an economy plugin.

**Comment by Momshroom** [comment]
The fix you just posted in #615 also appears to fix this issue

**Comment by Rocologo** [comment]
Fixed in 7.0.1
